language: node_js
node_js:
  # - "iojs"
  - "7"
before_install:
  - openssl aes-256-cbc -K $encrypted_33c2a12ca10a_key -iv $encrypted_33c2a12ca10a_iv -in travis_deploy.pub.enc -out travis_deploy.pub -d

cache:
  directories:
    - node_modules

deploy:
  skip_cleanup: true

after_success:
  - rm .gitignore && git add . && git commit -m 'deploy'
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 travis_deploy.pub # this key should have push access
  - ssh-add travis_deploy.pub # .travis/
  - git remote add deploy root@206.189.124.103/var/repo/site.git
  - git push deploy

