language: node_js
node_js:
  - "7"

before_install:
  - openssl aes-256-cbc -K $encrypted_33c2a12ca10a_key -iv $encrypted_33c2a12ca10a_iv -in .travis/travis_deploy.pem.enc -out travis_deploy.pem -d
  - openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in .travis/config.json.enc -out config.json -d

# before_script:
#   - npm run build

cache:
  directories:
    - node_modules

addons:
  ssh_known_hosts: 138.197.105.128

after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 travis_deploy.pem # this key should have push access
  - ssh-add travis_deploy.pem
  - rsync -r --delete-after --quiet . root@138.197.105.128:/root/ptjob-expressjs/
